print("Hello")

try:
  2/0
finally:
  print("catch-all errors")
